### PR TITLE
Setup to use React

### LINKED ISSUE #2: Setup project structure
**Setup and configure the frontend for the project to enable other works to be started.**

This involves the installation and setup of React and other required dependencies required for the frontend, ready to start consuming the backend endpoints.

### PR DESCRIPTION
**Pull request by fisayo-rm**
## Description
Set up project structure for React

Fixes #2 

## How Has This Been Tested?
Running npm install to install dependencies and npm start to open browser at [http://localhost:1234](http://localhost:1234)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bytenaija** [comment]
LGTM

**Review by bytenaija — APPROVED** [review]

**Comment by Techiefrankie** [comment]
@fisayo-DMG Please change the expression Fixes #(issue number 1) to Fixes #2 

Also, add another reviewer to make up the 3 required to approve a PR.

I discovered that you did not create a feature branch for this feature. You cannot work on the develop branch. You should create a feature branch like ft-setup-react from develop branch. Then after all work is done on ft-setup-react, you push to github and create a PR from ft-setup-react to develop. 

Please kindly close this PR and do it properly.
Thank you.

**Comment by fisayo-rm** [comment]
> @fisayo-DMG Please change the expression Fixes #(issue number 1) to Fixes #2
> 
> Also, add another reviewer to make up the 3 required to approve a PR.
> 
> I discovered that you did not create a feature branch for this feature. You cannot work on the develop branch. You should create a feature branch like ft-setup-react from develop branch. Then after all work is done on ft-setup-react, you push to github and create a PR from ft-setup-react to develop.
> 
> Please kindly close this PR and do it properly.
> Thank you.

I actually did create the branch locally but I forgot and merged to my develop before pushing. I'll do that now.

**Comment by Techiefrankie** [comment]
Please don't merge it to your local develop branch, you should not touch develop at all. Just do a push from your feature branch and then create a PR to develop on github. After merging, the next time you do a pull, your develop would be updated. @fisayo-DMG

**Comment by fisayo-rm** [comment]
> Please don't merge it to your local develop branch, you should not touch develop at all. Just do a push from your feature branch and then create a PR to develop on github. After merging, the next time you do a pull, your develop would be updated. @fisayo-DMG

okay, thanks.

**Review by Techiefrankie — APPROVED** [review]
Great, well done.

**Pull request merged**
